NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 9999						   
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.00     
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 15000000
NDefines.NNavy.ADMIRAL_TASKFORCE_CAP = 0
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 0